export const SET_CURRENT_DATE = 'SET_CURRENT_DATE'
export const SET_CURRENT_WEEK = 'SET_CURRENT_WEEK'
export const SET_JOURNAL_ENTRIES = 'SET_JOURNAL_ENTRIES'
export const SET_SETTINGS = 'SET_SETTINGS'